### ISSUE TITLE
cli code health and report code health mismatch

### ISSUE THREAD

**Issue by rrd108** [brenoepics/vmd-action#27]
![Képernyőkép 2024-09-30 18-32-22](https://github.com/user-attachments/assets/0be98ff3-3ea3-42be-ab51-0a54ed3a4749)

I got this code health on a PR I created.

But If I download the full report the code health is **97**, not **99**

**Comment by brenoepics** [comment]
Right now, the comment is only looking at PR changes, but the full report covers everything. Since the PR health is 99 and the full repo health is 97, we have two options:

1. **Change the Full Report Metric**: Make the full report match the PR's code health.
2. **Introduce Separate Metrics**: Use `fullCodeHealth` for the full report and `PRCodeHealth` for the PR.

Does this work for you? Or do you have any other suggestions?

**Comment by rrd108** [comment]
I like the 2nd approach as it adds more information.

Do you need anything from our side?
